### ISSUE TITLE
problem in cmake ..

### ISSUE THREAD

**Issue by zhanghaojia123456** [RavenCommunity/kawpowminer#26]
After git clone the project, and did something according to README file, in cmake .. stage, there is no further progress and stop at "-- [hunter] OPENSSL_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.1.1c)". 
How can I solve the problem?

myname@study:~$ cd kawpowminer/
myname@study:~/kawpowminer$ cd build/
myname@study:~/kawpowminer/build$ cmake ..
-- [cable ] Cable 0.2.14 initialized
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [cable ] Build type: Release
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /home/myname/.hunter
-- [hunter] [ Hunter-ID: e14bc15 | Toolchain-ID: c8e86b7 | Config-ID: e6a953b ]
-- [hunter] BOOST_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.70.0-p0)
-- [hunter] BOOST_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.70.0-p0)
-- [hunter] BOOST_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.70.0-p0)
-- [hunter] BOOST_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.70.0-p0)
-- Boost version: 1.70.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- [hunter] JSONCPP_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.8.0)
-- [hunter] ETHASH_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.0.0)
----------------------------------------------------------------------------
-- CMake 3.13.3
-- Build Release / Linux
----------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                      ON
-- ETHASHCUDA       Build CUDA components                        ON
-- ETHASHCPU        Build CPU components (only for development)  OFF
-- ETHDBUS          Build D-Bus components                       OFF
-- APICORE          Build API Server components                  ON
-- DEVBUILD         Build with dev logging                       OFF
----------------------------------------------------------------------------

-- Performing Test ffunction-sections
-- Performing Test ffunction-sections - Success
-- Performing Test fdata-sections
-- Performing Test fdata-sections - Success
-- Performing Test Wl,--gc-sections
-- Performing Test Wl,--gc-sections - Success
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- [hunter] OPENSSL_ROOT: /home/myname/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.1.1c)

**Comment by AndreaLanfranchi** [comment]
To build openssl you need to have perl installed.
Check for it.

**Comment by zhanghaojia123456** [comment]
I installed perl as below
wget https://www.cpan.org/src/5.0/perl-5.28.2.tar.gz
 tar -xzf perl-5.28.2.tar.gz
 cd perl-5.28.2
 ./Configure -des -Dprefix=$HOME/localperl
 make
 make test
 make install.

perl --version 
"This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
(with 46 registered patches, see perl -V for more detail)

Copyright 1987-2019, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.".

But executing cmake still stops at:
....
-- Performing Test Wl,--gc-sections - Success
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- [hunter] OPENSSL_ROOT: /home/mint/.hunter/_Base/e14bc15/c8e86b7/e6a953b/Install (ver.: 1.1.1c)

**Comment by zhanghaojia123456** [comment]
I found the code stop at "hunter_add_package(OpenSSL)" in /libpoolprotocols/CMakeLists.txt. but I don't know how to solve.

**Comment by zhanghaojia123456** [comment]
problem solved

**Comment by AndreaLanfranchi** [comment]
For reference to others would be nice if you could share how did you solved it.
Thank you

**Comment by Bolle-VVout** [comment]
Prob. waited long enough till hunter package is downloaded.
