### ISSUE TITLE
solved.

### ISSUE THREAD

**Issue by ethanchinaski** [RavenCommunity/kawpowminer#31]
The Miner is self compiled on Win 10 with Cuda 10.2. nothing changed, compiling finished without errors.
Compiling was done on Commandline, no GUI used. All done by the exact explanation written here.

machine: Ryzen 5 3600 Overclocked to 4Ghz 16 Gb DDR4 Ram 3200,
Palit GeForce RTX 2060 Super Gaming Pro OC 8GB the Card is OC by delivery, no changes made from me.
clock frequency: 1470 MHz
Gpu Boost-Clock: 1710 MHz
Stream processors: 2176
Effective Clockt: 14 GHz

Hashrate shown was 20 mh, effective Hashrate up to 35 Mh depending on the difficulty.
The days before the miner was running without any Problems, the same with a Linux compilation on ubuntu 20.04, no problems till today

Startup with these parameters, 
 kawpowminer.exe -P stratum+tcp://name.worker:passwd@rvn.suprnova.cc:8888  --cu-schedule auto --cu-streams 8 --cu-parallel-hash 8 --diff 365
miner was running for 1 Hour and 30 minutes then the following happened

 i 09:10:44 <unknown> ****Accepted  34 ms. rvn.suprnova.cc [5.39.65.109:8888]**
 i 09:10:45 <unknown> New target set to: 00000013ec000000000000000000000000000000000000000000000000000000
 i 09:10:45 <unknown> Epoch : 167 Difficulty : 215.59 Mh
 i 09:10:45 <unknown> Job: 7c954d0c... block 1252500 rvn.suprnova.cc [5.39.65.109:8888]
cu 09:10:46 cuda-0    Job: 2457c8a6... Sol: 0xd9c7b700372bbf94
cu 09:10:46 cuda-0    Generating DAG + Light : 2.34 GB
 m 09:10:47 <unknown> 1:45 A539:R2 20.81 Mh - cu0 20.81
**X 09:10:47 <unknown> Reject reason : 20 job not found
 X 09:10:47 <unknown> **Rejected  26 ms. rvn.suprnova.cc [5.39**
 m 09:10:52 <unknown> 1:45 A539:R3 20.81 Mh - cu0 20.81
cu 09:10:54 cuda-0    Generated DAG + Light in 7.945 ms. 5.66 GB left.
cu 09:10:54 cuda-0    Launching period 417.500 ProgPow kernel
cu 09:10:54 cuda-0    Pre-compiled period 417.501 CUDA ProgPow kernel for arch 7.5
 m 09:10:57 <unknown> 1:45 A539:R3 7.39 Mh - cu0 7.39
 m 09:11:02 <unknown> 1:45 A539:R3 19.55 Mh - cu0 19.55
cu 09:11:03 cuda-0    Job: 7c954d0c... Sol: 0xd9c7b7000ad44a94
 X 09:11:04 **<unknown> GPU 0 gave incorrect result. Lower overclocking values if it happens frequently.**
cu 09:11:07 cuda-0    Job: 7c954d0c... Sol: 0xd9c7b7000f33220c
 X 09:11:07 <unknown> GPU 0 gave incorrect result. Lower overclocking values if it happens frequently.
 m 09:11:07 <unknown> 1:45 A539:R3:F2 19.91 Mh - cu0 19.91
 m 09:11:12 <unknown> 1:45 A539:R3:F2 19.89 Mh - cu0 19.89
 m 09:11:17 <unknown> 1:45 A539:R3:F2 19.92 Mh - cu0 19.92
 m 09:11:22 <unknown> 1:45 A539:R3:F2 19.91 Mh - cu0 19.91
cu 09:11:23 cuda-0    Job: 7c954d0c... Sol: 0xd9c7b70022dce449
 X 09:11:23 <unknown> GPU 0 gave incorrect result. Lower overclocking values if it happens frequently.
 m 09:11:27 <unknown> 1:46 A539:R3:F3 19.90 Mh - cu0 19.90

after that it took me 1 hour to recognize that the miner did not found any share at all after the one share was rejected
I tried to reproduce this event, but at the moment after 2 hours of running the min er i had 2 rejected shares and the miner works properly..
could this be juist a coincedence and had nothing to do with the rejected share ?

**Comment by ethanchinaski** [comment]
seemed to be a single event and not software related, so done

**Comment by kmich411** [comment]
I just had this same issue.." GPU 0 gave incorrect result. Lower overclocking values if it happens frequently." in 2 separate locations
