### ISSUE TITLE
Continuous buzzing from computer while running miner...

### ISSUE THREAD

**Issue by ryanniehaus** [RavenCommunity/kawpowminer#32]
I get a strange buzzing sound when running this.  I'm not sure if it's an internal speaker on the PC or a fan, but it sounds like it may actually be data being played through a speaker.  (Like trying to play a data CD on a normal CD player)

Command I'm using:
`kawpowminer -U -P stratum+tcp://RRiP8RffTx8swacrPfavcm22hCYrTRNEeg@rvn-eu1.nanopool.org:12222`

Command Output:
```


kawpowminer 1.2.3+commit.d46045ef
Build: windows/release/msvc

 i 12:12:25 main      Configured pool rvn-eu1.nanopool.org:12222
 i 12:12:25 <unknown> Selected pool rvn-eu1.nanopool.org:12222
 i 12:12:26 <unknown> Stratum mode : Stratum
 i 12:12:26 <unknown> Established connection to rvn-eu1.nanopool.org [213.32.74.219:12222]
 i 12:12:26 <unknown> Spinning up miners...
cu 12:12:26 cuda-0    Using Pci Id : 01:00.0 GeForce RTX 2080 SUPER (Compute 7.5) Memory : 8.00 GB
cu 12:12:26 cuda-1    Using Pci Id : 02:00.0 GeForce GTX 750 Ti (Compute 5.0) Memory : 8.00 GB
 i 12:12:26 <unknown> Extranonce set to 552412
 i 12:12:26 <unknown> New target set to: 0000000e5109ec205d7bea6a7ad66e448f8a5a6fc66fc9cac81e1fb408bef988
 i 12:12:26 <unknown> Authorized worker RRiP8RffTx8swacrPfavcm22hCYrTRNEeg
 i 12:12:26 <unknown> Epoch : 168 Difficulty : 300.00 Mh
 i 12:12:26 <unknown> Job: 87062ed2... block 1260238 rvn-eu1.nanopool.org [213.32.74.219:12222]
cu 12:12:27 cuda-1    Generating DAG + Light : 2.35 GB
cu 12:12:27 cuda-0    Generating DAG + Light : 2.35 GB
cu 12:12:27 cuda-1    Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch_internal at line 138 calling cudaMalloc(reinterpret_cast<void**>(&m_device_dag), m_epochContext.dagSize) failed with error out of memory on CUDA device 02:00.0
cu 12:12:27 cuda-1    Mining suspended ...
 m 12:12:30 <unknown> 0:00 A0 0.00 h - cu0 0.00, cu1 0.00
cu 12:12:34 cuda-0    Generated DAG + Light in 7,653 ms. 5.65 GB left.
cu 12:12:35 cuda-0    Pre-compiled period 420,079 CUDA ProgPow kernel for arch 7.5
```

There's more output, I only copy-pasted where the buzzing starts...
As soon as I stop the program, the buzzing stops.  Mining seems to be working, I've gotten some shares.  I just can't do it because the buzzing is too annoying.  I've run my machine through benchmarking and played some pretty advanced games on it with max settings, never had this issue  with anything else.

I know it's probably an unusual issue no one's reported before, but it'd be great if you could give some insight.

**Comment by ryanniehaus** [comment]
I did a little more research, looked into BIOS settings.  I'm wondering if this is some sort of temperature alarm.
Is there a way to limit temperature like I've seen on other miners for other algorithms?

**Comment by ethanchinaski** [comment]
you use a 2080 super and a 750 ti at once,  and the Cuda error is because the 750 ti just has 2GB RAM, that is not enough to mine ravencoin. so the error comes from that.
Means this grafic card is much to low to run aside the 2080 RTX, and the ravenminer dont even scratch the surface of that what the 2080 is capable of, you dont need the 750, run your machine without it and see if its working then

**Comment by ryanniehaus** [comment]
I ran the as you said and it still happened.

lol... so the sound was actually coming from my UPS.  I was at max power load.  Looks like the miner is the most intensive thing I've actually run on my new computer.  I'll have to upgrade my UPS before I do any serious mining.  Nice app!
