### ISSUE TITLE
kawpowminer windows not opening

### ISSUE THREAD

**Issue by Vanishy** [RavenCommunity/kawpowminer#34]
sirs/maams please help with kawpowminer im on windows and  i try to open it not open it show for like .1 millisecond then close pls help im serious i want to mine bitcoin

**Comment by skydivematy** [comment]
This is Not a BITCOIN Miner...
For Bitcoin you need an Asic Miner.

**Comment by Vanishy** [comment]
what u mean then what does this mine????

**Comment by AndreaLanfranchi** [comment]
This is for RavenCoin mining. A completely different coin even though inherited from Bitcoin.
Bitcoin mining is mostly done using specialized hardware (ASICs) while RavenCoin has embraced GPU mining.
