### ISSUE TITLE
CUDA11.0.2 build error

### ISSUE THREAD

**Issue by one-won** [RavenCommunity/kawpowminer#35]
OS : CentOS8

CUDA10.0 : good
CUDA10.2 : good
CUDA11.0.1 : good
CUDA11.0.2 : error

![VirtualBox_CentOS8_05_08_2020_14_21_00](https://user-images.githubusercontent.com/50016405/89376272-6b7a5900-d72a-11ea-9627-5c896acd6b4c.png)

**Comment by theezgyms** [comment]
its not meant to work with cuda 11 my friend. So ise 10.2. if I install cuda 11 No miner picks up gpu's or works nbminer gminer kawpowminer and  cuda 11 is more specifically made for nvidia a100 the new architecture so like volta cards most prefer 10.2

**Comment by xgnom666x** [comment]
In the file /libethash-cuda/СMakeLists.tхt, delete or comment out lines with unnecessary architectures.
Like that:

```
if(COMPUTE AND (COMPUTE GREATER 0))`
  list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_${COMPUTE},code=sm_${COMPUTE}")
else()
    list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_61,code=sm_61")
    list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_62,code=sm_62")
    #if(NOT CUDA_VERSION VERSION_LESS 9.0)
    #   list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_70,code=sm_70")
    #endif()
    #if(NOT CUDA_VERSION VERSION_LESS 10.0)
    #   list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_75,code=sm_75")
    #endif()
endif()
```
PS.It wokrs for ethminer, I think it will work here too. Sorry for my english.
PPS.Ubuntu 18.04, Cuda 11.0.3.

**Comment by one-won** [comment]
> In the file /libethash-cuda/СMakeLists.tхt, delete or comment out lines with unnecessary architectures.
> Like that:
> 
> ```
> if(COMPUTE AND (COMPUTE GREATER 0))`
>   list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_${COMPUTE},code=sm_${COMPUTE}")
> else()
>     list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_61,code=sm_61")
>     list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_62,code=sm_62")
>     #if(NOT CUDA_VERSION VERSION_LESS 9.0)
>     #   list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_70,code=sm_70")
>     #endif()
>     #if(NOT CUDA_VERSION VERSION_LESS 10.0)
>     #   list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_75,code=sm_75")
>     #endif()
> endif()
> ```
> 
> PS.It wokrs for ethminer, I think it will work here too. Sorry for my english.
> PPS.Ubuntu 18.04, Cuda 11.0.3.
> 
> Update(4:20 pm):
> Works . Just built for 1070

Wow! Works. Thank you for the good teaching.
