### ISSUE TITLE
GeForce 1050 GTX Ti working?

### ISSUE THREAD

**Issue by tobiashaas** [RavenCommunity/kawpowminer#36]
hey,

i would like to mine some RVN, everything is working but my Graphic Card is sleeping :-D
Is GeForce 1050 GTX Ti compatible?

`kawpowminer 1.2.3+commit.d46045ef
Build: windows/release/msvc

 i 10:43:20 main      Configured pool rvn-eu1.nanopool.org:12222
 i 10:43:20 <unknown> Selected pool rvn-eu1.nanopool.org:12222
 i 10:43:20 <unknown> Stratum mode : Stratum
 i 10:43:20 <unknown> Established connection to rvn-eu1.nanopool.org [92.222.10.59:12222]
 i 10:43:20 <unknown> Spinning up miners...
cu 10:43:20 cuda-0    Using Pci Id : 01:00.0 GeForce GTX 1050 Ti (Compute 6.1) Memory : 4.00 GB
 i 10:43:20 <unknown> Extranonce set to 2f356b
 i 10:43:20 <unknown> New target set to: 0000000e5109ec205d7bea6a7ad66e448f8a5a6fc66fc9cac81e1fb408bef988
 i 10:43:20 <unknown> Authorized worker RNggftRALAix4gT34vDNnrPGKdsvPoeMeh.hobbele
 i 10:43:20 <unknown> Epoch : 185 Difficulty : 300.00 Mh
 i 10:43:20 <unknown> Job: 60f52aef... block 1388456 rvn-eu1.nanopool.org [92.222.10.59:12222]
cu 10:43:22 cuda-0    Generating DAG + Light : 2.48 GB
 i 10:43:23 <unknown> Job: 2779fab7... block 1388456 rvn-eu1.nanopool.org [92.222.10.59:12222]
 m 10:43:25 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 10:43:29 <unknown> Job: 961ffb50... block 1388456 rvn-eu1.nanopool.org [92.222.10.59:12222]`

**Comment by nyakze** [comment]
It should work, there's nothing in the logs except it saying that gpu is generating DAG, you need to wait for that process to complete before hashing starts.
