### ISSUE TITLE
error build kawpowminer

### ISSUE THREAD

**Issue by toptim** [RavenCommunity/kawpowminer#4]
ubuntu 16, cuda 9.2 -DETHASHCL=OFF -DETHASHCUDA=ON
`Scanning dependencies of target kawpowminer
Building CXX object kawpowminer/CMakeFiles/kawpowminer.dir/main.cpp.o
Linking CXX executable kawpowminer
../libethcore/libethcore.a(Farm.cpp.o): In function `dev::eth::Farm::spawn_file_in_bin_dir(char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
Farm.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE+0x79): undefined reference to `boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*)'
Farm.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE+0xcd): undefined reference to `boost::filesystem::path::parent_path() const'
Farm.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE+0x1f9): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
Farm.cpp:(.text._ZN3dev3eth4Farm21spawn_file_in_bin_dirEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EE+0x284): undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
../libhwmon/libhwmon.a(wrapamdsysfs.cpp.o): In function `void boost::sp_adl_block::intrusive_ptr_release<boost::filesystem::detail::dir_itr_imp, boost::sp_adl_block::thread_safe_counter>(boost::sp_adl_block::intrusive_ref_counter<boost::filesystem::detail::dir_itr_imp, boost::sp_adl_block::thread_safe_counter> const*)':
wrapamdsysfs.cpp:(.text._ZN5boost12sp_adl_block21intrusive_ptr_releaseINS_10filesystem6detail11dir_itr_impENS0_19thread_safe_counterEEEvPKNS0_21intrusive_ref_counterIT_T0_EE[_ZN5boost12sp_adl_block21intrusive_ptr_releaseINS_10filesystem6detail11dir_itr_impENS0_19thread_safe_counterEEEvPKNS0_21intrusive_ref_counterIT_T0_EE]+0x18): undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
../libhwmon/libhwmon.a(wrapamdsysfs.cpp.o): In function `boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&)':
wrapamdsysfs.cpp:(.text._ZN5boost10filesystem18directory_iteratorC2ERKNS0_4pathE[_ZN5boost10filesystem18directory_iteratorC5ERKNS0_4pathE]+0x6c): undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
../libhwmon/libhwmon.a(wrapamdsysfs.cpp.o): In function `wrap_amdsysfs_create()':
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x7f): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x9e): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x317): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x32e): undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x412): undefined reference to `boost::filesystem::path::filename() const'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x6af): undefined reference to `boost::filesystem::path::filename() const'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x913): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x92c): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xc96): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xcb4): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xd3a): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xd52): undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xe55): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xe71): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0xebd): undefined reference to `boost::filesystem::path::filename() const'
wrapamdsysfs.cpp:(.text._Z20wrap_amdsysfs_createv+0x116a): undefined reference to `boost::filesystem::path::filename() const'
collect2: error: ld returned 1 exit status
kawpowminer/CMakeFiles/kawpowminer.dir/build.make:116: recipe for target 'kawpowminer/kawpowminer' failed
make[2]: *** [kawpowminer/kawpowminer] Error 1
CMakeFiles/Makefile2:526: recipe for target 'kawpowminer/CMakeFiles/kawpowminer.dir/all' failed
make[1]: *** [kawpowminer/CMakeFiles/kawpowminer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by toptim** [comment]
and minor error in EthStratumClient
`[ 79%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/stratum/EthStratumClient.cpp.o
/kawpowminer/libpoolprotocols/stratum/EthStratumClient.cpp: In member function ‘void EthStratumClient::processResponse(Json::Value&)’:
/kawpowminer/libpoolprotocols/stratum/EthStratumClient.cpp:1328:26: warning: unused variable ‘fCancelJob’ [-Wunused-variable]
                     bool fCancelJob = jPrm.get(Json::Value::ArrayIndex(prmIdx++), "").asBool();
`

**Comment by traysi** [comment]
Thank you for this report, update pushed to resolve this.
