### ISSUE TITLE
Files missing from source

### ISSUE THREAD

**Issue by bananeVaudou** [RavenCommunity/kawpowminer#41]
In order to build version 1.2.3 from source on Windows 10 64bit with VS 2019:

1. kawpowminer-1.2.3\cmake\cable folder is empty : it must be populated with [this](https://github.com/ethereum/cable.git)

2. In CMakeList.txt :

`cable_set_build_type(DEFAULT Release CONFIGURATION_TYPES Release RelWithDebInfo)`

must be placed before : 

`project(kawpowminer)`

Otherwise, cable complains that "cable_set_build_type() must be used before project()".

**Comment by aydwi** [comment]
`git submodule update --init --recursive` at the project root
