### ISSUE TITLE
RTX 3090 not working

### ISSUE THREAD

**Issue by qinapps** [RavenCommunity/kawpowminer#43]
on the RTX3090 I have following error:
#Unexpected error CUDA error in func set_constants at line 180 calling cudaMemcpyToSymbol(d_dag, &_dag, sizeof(hash64_t*)) failed with error invalid device symbol on CUDA device 02:00.0

some ideas?

**Comment by joemarkets** [comment]
Join the Ravencoin discord this is not a place for this type of question. It’s a driver problem or a overclock issue

**Comment by qinapps** [comment]
sorry no this lines are missing in CMakeLists

 		# NVIDIA A100 and NVIDIA DGX-A100
 		list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_80,code=sm_80")
 	endif()
 	if(NOT CUDA_VERSION VERSION_LESS 11.1)
 		# Tesla GA10x cards, RTX Ampere – RTX 3080/3090, RTX A6000, RTX A40
 		list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
 	endif()

**Comment by greenku** [comment]
Was this issue solved? Having a similar issue with latest version and a RTX-3070. I edited the CMakeLists file adding the line "list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86"" and that allows cmake to finish but when starting up kawpowminer I get;
cu 02:58:26 cuda-2    Using Pci Id : 04:00.0 GeForce RTX 3070 (Compute 8.6) Memory : 7.79 GB
cu 02:58:26 cuda-2    Could not set CUDA device on Pci Id 04:00.0 Error : CUDA error in func initDevice at line 69 calling cuDevicePrimaryCtxRelease(m_device) failed with error CUDA_ERROR_INVALID_CONTEXT
cu 02:58:26 cuda-2    Mining aborted on this device.

**Comment by geoffroyp** [comment]
Same problem here with a 3090. I'm using winbdows 10 version of kawpow miner.

The file mentionned above (CMakeLists) is not included in this release :/

**Comment by geemodo** [comment]
Just adding information  Fails to detect Nvidia 3090 (ZOTAC GAMING GeForce RTX 3090 Trinity)

**Comment by fdoving** [comment]
Should be fixed with 4718b079756d44a48c1333e55fdeef65c7e12e99

Please test and give feedback.
