### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Antonio6666** [RavenCommunity/kawpowminer#44]
Hello,

building from source I got the following error:
kawpowminer nvcc fatal   : Unsupported gpu architecture 'compute_30'

Until a mounth ago I was able to succesfully  build from source.
I'm  running Debian Sid here my command:
cd kawpowminer
git submodule update --init --recursive
mkdir build
cd build
cmake .. -DETHASHCUDA=ON -DCUDA_cuda_LIBRARY=/usr/lib/x86_64-linux-gnu/libcuda.so  -DCUDA_nvrtc_LIBRARY=/usr/lib/x86_64-linux-gnu/libnvrtc.so  -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_C
XX_COMPILER=g++-8
make -sj $(nproc)

thanks
Antonio

**Comment by one-won** [comment]
https://github.com/RavenCommunity/kawpowminer/issues/35#issue-673270909

**Comment by Antonio6666** [comment]
Editing the libethash-cuda/CMakeLists.txt file as one-won comment (comment out compute_30 row) the buildinng  is ok  but it works only for cuda-0.
For the second device cuda-1 i got :

cu 12:07:26 cuda-0    Using Pci Id : 08:00.0 GeForce GTX 1070 Ti (Compute 6.1) Memory : 7.93 GB
cu 12:07:26 cuda-1    Using Pci Id : 09:00.0 GeForce GTX 1070 Ti (Compute 6.1) Memory : 7.93 GB
**cu 12:07:26 cuda-1    Could not set CUDA device on Pci Id 09:00.0 Error : CUDA error in func initDevice at line 69 calling cuDevicePrimaryCtxRelease(m_device) failed with error CUDA_ERROR_INVALID_CONTEXT**

Is there a  solution for this error?

Many Thanks
Antonio

**Comment by greenku** [comment]
Was this issue solved? I have a similar issue with RTX-3070 cards after editing the CMakeFiles as referenced above.

**Comment by one-won** [comment]
Check this
https://docs.nvidia.com/cuda/ampere-compatibility-guide/index.html#building-applications-with-ampere-support

**Comment by greenku** [comment]
Checking a bit deeper into the issue, it appears to not have anything to do with the RTX-3070 card, but possibly the PCI ID? My rig has three Nvidia cards;

$ sudo lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation GA104 [GeForce RTX 3070] (rev a1)
02:00.0 VGA compatible controller: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] (rev a1)
04:00.0 VGA compatible controller: NVIDIA Corporation GA104 [GeForce RTX 3070] (rev a1)
$ sudo nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04 Driver Version: 460.27.04 CUDA Version: 11.2 |
|-------------------------------+----------------------+----------------------+

When I use the option --cuda-devices 0, mining starts as expected on the RTX-3070;

cu 10:53:59 cuda-0 Using Pci Id : 01:00.0 GeForce RTX 3070 (Compute 8.6) Memory : 7.79 GB
i 10:53:59 kawpowminer Extranonce set to 932d6f
i 10:53:59 kawpowminer Authorized worker RTEH5i1px9f7wFokWzJPVZzfjW2kR6QS7f.rig01
i 10:53:59 kawpowminer New target set to: 00000009f6000000000000000000000000000000000000000000000000000000
i 10:54:00 kawpowminer Epoch : 219 Difficulty : 431.17 Mh
i 10:54:00 kawpowminer Job: 4a6906d3… block 1649468 stratum-ravencoin.flypool.org [[2606:4700:90:0:e25:aa88:c382:143a]:3443]
cu 10:54:02 cuda-0 Generating DAG + Light : 2.75 GB
m 10:54:04 kawpowminer 0:00 A0 0.00 h - cu0 0.00
cu 10:54:07 cuda-0 Generated DAG + Light in 4,787 ms. 5.04 GB left.
cu 10:54:08 cuda-0 Pre-compiled period 549,822 CUDA ProgPow kernel for arch 8.6
cu 10:54:08 cuda-0 Launching period 549,822 ProgPow kernel
cu 10:54:08 cuda-0 Pre-compiled period 549,823 CUDA ProgPow kernel for arch 8.6
m 10:54:09 kawpowminer 0:00 A0 28.48 Kh - cu0 28.48

When I use the option --cuda-devices 1 (or 2) to try and start mining on the other two cards I get;

cu 10:55:44 cuda-0 Using Pci Id : 02:00.0 GeForce RTX 2060 (Compute 7.5) Memory : 7.79 GB
i 10:55:44 kawpowminer Extranonce set to 932e58
cu 10:55:44 cuda-0 Could not set CUDA device on Pci Id 02:00.0 Error : CUDA error in func initDevice at line 69 calling cuDevicePrimaryCtxRelease(m_device) failed with error CUDA_ERROR_INVALID_CONTEXT
cu 10:55:44 cuda-0 Mining aborted on this device.

i 10:56:11 kawpowminer Spinning up miners...

cu 10:56:11 cuda-0 Using Pci Id : 04:00.0 GeForce RTX 3070 (Compute 8.6) Memory : 7.79 GB

cu 10:56:11 cuda-0 Could not set CUDA device on Pci Id 04:00.0 Error : CUDA error in func initDevice at line 69 calling cuDevicePrimaryCtxRelease(m_device) failed with error CUDA_ERROR_INVALID_CONTEXT

i 10:56:11 kawpowminer Extranonce set to 932e99

cu 10:56:11 cuda-0 Mining aborted on this device.

I get the aborted message when I try and start a single instance the miner trying to use all three cards. Mining does start on card 0 (the first RTX-3070) when I start a single instance using three cards.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by greenku** [comment]
additional information... I have built ethminer using the same machine and CUDA version and ethminer works fine with the three cards in my earlier post.

**Comment by Antonio6666** [comment]
Whot do you mean for "same machine and CUDA version" ?

**Comment by greenku** [comment]
My understanding is that kawpowminer originated from ethminer. I have one version of CUDA installed on the machine, 11.2. I have two 3070s and one 2060 in the machine. After building both ethminer and kawpowminer on this machine, ethminer works and kawpowminer does not. Other than building ethminer, I did not change anything else.

Seems to be an issue with the kawpowminer code and not CUDA or the GPUs. I am reviewing the kawpowminer code, but I am not proficient in C++

**Comment by fdoving** [comment]
Should be fixed with 1bb74da6a6028db1ce82160040fbc58745b98144

Please test and give feedback.

**Comment by greenku** [comment]
I downloaded the latest release, recompiled and can confirm three GPUs are working fine. Thanks!
