### ISSUE TITLE
kawpowminer for opencl need libnvrtc.so.10.2

### ISSUE THREAD

**Issue by shatll-s** [RavenCommunity/kawpowminer#5]

**Comment by circut22** [comment]
will there be a amd relase for windows 10? or do i need to build in windows?

**Comment by vudutech** [comment]
Have a similar problem with Ubunutu 18.04 and Vega 56.

AMD drivers installed with "amdgpu-pro-install -y --opencl=pal,legacy"

**Comment by Css-IanM** [comment]
and drivers dont include cuda, it should be trying to load that lib, but it is. Version 1.0 had a amd only build but subsequent build did not.

**Comment by shiggid** [comment]
Tried to run kawpowminer on Ubuntu 16.04 getting this error:
./kawpowminer: error while loading shared libraries: libnvrtc.so.10.2: cannot open shared object file: No such file or directory

What do I need to do to fix this?

**Comment by Bolle-VVout** [comment]
Best is to build a version that suits your cuda version or install cuda 10.2. Steps are well described in the quick installation manual on the nvidia site if you want to update your cuda.

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=runfilelocal

**Comment by nyakze** [comment]
I don't think it should require CUDA at all for OpenCL only build. That's the point.

**Comment by Bolle-VVout** [comment]
You compiled the project with "cmake .. DETHASHCUDA=OFF" then? otherwise the compilation is involving cuda into it. I had to empty my build dir to accept the new cmake variables first btw.

**Comment by jeroz1** [comment]
> 
> 
> You compiled the project with "cmake .. DETHASHCUDA=OFF" then? otherwise the compilation is involving cuda into it. I had to empty my build dir to accept the new cmake variables first btw.

Solution presented, closing.
