### ISSUE TITLE
Is GTX 660Ti suported by kawpowminer

### ISSUE THREAD

**Issue by Szusty666** [RavenCommunity/kawpowminer#50]
I try to use it but without luck:
![image](https://user-images.githubusercontent.com/78966025/107775935-dd1a0c00-6d38-11eb-8755-3d39774cc556.png)

This is the second GPU so all memory should be available to used.

**Comment by netomx** [comment]
2GB < 2.73 GB required.

**Comment by jeroz1** [comment]
Your card does not have enough memory available to mine kawpow.
