### ISSUE TITLE
Solo mining ravencoin 

### ISSUE THREAD

**Issue by sachinverma1** [RavenCommunity/kawpowminer#55]
Hi community,

I want to mine solo on ravend or raven-qt.
Can anyone help me to find out how to mine raven solo on daemon. Any article or something will be helpful. 

Or if you can tell me does kawpow miner works solo or not?

Thank you.

**Comment by MoarCryptoPlz** [comment]
kawpow mining works on solo with Nvidia, have not tested it on AMD, although it should work fine.

**Comment by sachinverma1** [comment]
Hi,

Thank you for your reply. I have Nvidia cards only..

But can I mine on daemon on my localhost?

Thank you

**Comment by fdoving** [comment]
Not supported. Use a pool.
