### ISSUE TITLE
Cannot build on Ubuntu 20.10 - nvcc fatal   : Unsupported gpu architecture 'compute_30'

### ISSUE THREAD

**Issue by alindece** [RavenCommunity/kawpowminer#59]
Hi community,

i am trying to build kawpowminer but i get this error, can you tell how can i fix it?
nvcc --version
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0

gcc -v
gcc version 10.2.0

[ 42%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_CUDAMiner_cuda.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at ethash-cuda_generated_CUDAMiner_cuda.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ndr/opt/kawpowminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_CUDAMiner_cuda.cu.o
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_CUDAMiner_cuda.cu.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:513: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Errore 2
make[1]: *** Attesa per i processi non terminati....
Scanning dependencies of target poolprotocols
[ 45%] Building CXX object libpoolprotocols/CMakeFiles/poolprotocols.dir/stratum/EthStratumClient.cpp.o
/home/ndr/opt/kawpowminer/libpoolprotocols/stratum/EthStratumClient.cpp: In member function ‘void EthStratumClient::processResponse(Json::Value&)’:
/home/ndr/opt/kawpowminer/libpoolprotocols/stratum/EthStratumClient.cpp:1394:26: warning: unused variable ‘fCancelJob’ [-Wunused-variable]
 1394 |                     bool fCancelJob = jPrm.get(Json::Value::ArrayIndex(prmIdx++), "").asBool();
      |                          ^~~~~~~~~~
[ 47%] Linking CXX static library libpoolprotocols.a
[ 65%] Built target poolprotocols
make: *** [Makefile:152: all] Errore 2

**Comment by alindece** [comment]
For the GeForce GTX 1080ti work fine but for Quadro K2200 I don't understand what architecture it has, it's not in that list.
Thank you for the good teaching.

**Comment by gap370** [comment]
https://www.techpowerup.com/gpu-specs/quadro-k2200.c2601
Maxwell

**Comment by quydau35** [comment]
you should remove cuda 11x and fallback to cuda <10.2 because compute_30 is deprecated and not support since 10.2.

**Comment by alindece** [comment]
thanks for the answers, I build correctly but i still get an error, i will try cuda <10.2

cu 18:32:14 cuda-0    Using Pci Id : 04:00.0 Quadro K2200 (Compute 5.0) Memory : 3.94 GB
cu 18:32:14 cuda-1    Using Pci Id : 05:00.0 Quadro K2200 (Compute 5.0) Memory : 3.94 GB
cu 18:32:14 cuda-1    Could not set CUDA device on Pci Id 05:00.0 Error : CUDA error in func initDevice at line 69 calling cuDevicePrimaryCtxRelease(m_device) failed with error CUDA_ERROR_INVALID_CONTEXT
cu 18:32:14 cuda-1    Mining aborted on this device

**Comment by fdoving** [comment]
duplicate #54
