### ISSUE TITLE
Error while running kawpow miner for raven coin

### ISSUE THREAD

**Issue by sachinverma1** [RavenCommunity/kawpowminer#60]
![IMG_20210305_004630](https://user-images.githubusercontent.com/31692463/110092990-3d442100-7dc0-11eb-9e68-d5ad2d65d41f.jpg)

Kindly help me with this error.

**Comment by marco-silvestri** [comment]
Same here, I have also tried a couple of different pools.

**Comment by sachinverma1** [comment]
I am not not mining at pool.. I am mining solo.. But there is no difference
mining at pool or solo.. It should work. I am using 8gb system ram and 4gb
gpu, and ravencoin makes DAG of around 2.5 gb so, according to that it
should work.

**Comment by fdoving** [comment]
Not supported, use a pool.
