### ISSUE TITLE
CUDA Error with RTX 3060

### ISSUE THREAD

**Issue by grenelt** [RavenCommunity/kawpowminer#61]
`Unexpected error CUDA error in func set_constants at line 180 calling cudaMemcpyToSymbol(d_dag, &_dag, sizeof(hash64_t*)) failed with error invalid device symbol on CUDA device 01:00.0`

Then kawpowminer stops mining.

**Comment by Spooky309** [comment]
CUDA 11 (which is required for RTX 3000 series GPUs) is not supported, see https://github.com/RavenCommunity/kawpowminer/issues/54
