### ISSUE TITLE
CMake error while building on windows

### ISSUE THREAD

**Issue by OfirIsakov** [RavenCommunity/kawpowminer#77]
Hey,
I'm new to the CMake world and especially hunter,
I have an RTX 3070 and I understand the miner still doesn't support CUDA 11.X, so I'm trying to build from source on `Windows`.
I have VS 19 and also installed Perl under `C:\Perl`.
I'm following the `README.md` windows build via the VS developer command prompt.
I'm getting a CMake error saying:
```
CMake Error at CMakeLists.txt:16 (hunter_add_package):
  Unknown CMake command "hunter_add_package".
```
Heres the full output of `cmake .. -DETHASHCUDA=ON`: https://pastebin.com/MPKPJb9Q
I didn't find a fix for windows at other issues, any ideas?

**Comment by jeroz1** [comment]
```
# Start in your home folder
cd %userprofile%

# Downloading the git repo of kawpow
git clone https://github.com/RavenCommunity/kawpowminer.git

# Enter the folder
cd kawpowminer

# Tell git to grab submodules needed for the installation
git submodule update --init --recursive

# Make a folder to move the build in
mkdir build

# Go into the folder
cd build

# Create the kawpow files for your windows system
cmake -G "Visual Studio 16 2019" -A X64 -H. -Bbuild -DETHASHCL=ON -DETHASHCUDA=ON -DAPICORE=ON ..

# Go into the newly made build folder
cd build

# Make the binaries for your system
cmake --build . --config Release
```

Does that help?

**Comment by OfirIsakov** [comment]
Yes!
Thank you this seems to do the job!
