### ISSUE TITLE
NVRTC_ERROR_BUILTIN_OPERATION_FAILURE, HIVEOS

### ISSUE THREAD

**Issue by castillojim24** [RavenCommunity/kawpowminer#8]
kawpowminer 1.1.3+commit.adb6e361
Build: linux/release/gnu

[94m i [35m21:22:03 [94mkawpow    [0mConfigured pool rvnt.minermore.com:4505
[94m i [35m21:22:03 [94mkawpow    [0mApi server listening on port 3334.
[94m i [35m21:22:03 [94mkawpow    [0mSelected pool rvnt.minermore.com:4505
[94m i [35m21:22:03 [94mkawpow    [0mStratum mode : Stratum
[94m i [35m21:22:03 [94mkawpow    [0mEstablished connection to rvnt.minermore.com [149.28.243.216:4505]
[94m i [35m21:22:03 [94mkawpow    [0mSpinning up miners...
[33mcu [35m21:22:03 [94mcuda-0    [0mUsing Pci Id : 01:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
[33mcu [35m21:22:03 [94mcuda-1    [0mUsing Pci Id : 04:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
[33mcu [35m21:22:03 [94mcuda-2    [0mUsing Pci Id : 06:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
[33mcu [35m21:22:03 [94mcuda-3    [0mUsing Pci Id : 09:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
[94m i [35m21:22:03 [94mkawpow    [0mNew target set to: 00000009f6000000000000000000000000000000000000000000000000000000
[94m i [35m21:22:03 [94mkawpow    [0mEpoch : [97m36[0m Difficulty : [97m431.17 Mh[0m
[94m i [35m21:22:03 [94mkawpow    [0mJob: [97maedaec7dâ€¦ block 275179[0m rvnt.minermore.com [149.28.243.216:4505]
[33mcu [35m21:22:03 [94mcuda-4    [0mUsing Pci Id : 0a:00.0 GeForce RTX 2070 (Compute 7.5) Memory : 7.93 GB
[33mcu [35m21:22:05 [94mcuda-1    [0mGenerating DAG + Light : 1.30 GB
[33mcu [35m21:22:05 [94mcuda-0    [0mGenerating DAG + Light : 1.30 GB
[33mcu [35m21:22:05 [94mcuda-2    [0mGenerating DAG + Light : 1.30 GB
[94m i [35m21:22:05 [94mkawpow    [0mAuthorized worker jimnu.1070s
[33mcu [35m21:22:05 [94mcuda-4    [0mGenerating DAG + Light : 1.30 GB
[33mcu [35m21:22:05 [94mcuda-3    [0mGenerating DAG + Light : 1.30 GB
[94m i [35m21:22:06 [94mkawpow    [0mJob: [97mf51faeffâ€¦ block 275180[0m rvnt.minermore.com [149.28.243.216:4505]
[94m i [35m21:22:08 [94mkawpow    [0mNew API session from 127.0.0.1:59540
[94m i [35m21:22:08 [94mkawpow    [0mAPI : Method miner_getstat1 requested
[32m m [35m21:22:08 [94mkawpow    [0m[32m0:00[0m[1;97m A0[0m [1;36m0.00 h[0m - cu0 [36m0.00[0m [36m45C 74%[0m, cu1 [36m0.00[0m [36m45C 75%[0m, cu2 [36m0.00[0m [36m47C 74%[0m, cu3 [36m0.00[0m [36m53C 75%[0m, cu4 [36m0.00[0m [36m45C 60%[0m
[33mcu [35m21:22:08 [94mcuda-4    [0mGenerated DAG + Light in 3,820 ms. 6.63 GB left.
terminate called after throwing an instance of 'cuda_runtime_error'
  what():  CUDA NVRTC error in func compileKernel at line 411 calling compileResult failed with error NVRTC_ERROR_BUILTIN_OPERATION_FAILURE

**Comment by blondfrogs** [comment]
@castillojim24 Is this is an issue. We have made lots of improvments and I know some users are using HIVE OS with no issues. 

Please try it with version 1.2.1 and see if you are successful :)

**Comment by castillojim24** [comment]
I try with hiveos customized version 1.2.0 and with 1.2.1 compiled by myself, but the error persist

**Comment by castillojim24** [comment]
Problem solved.

**Comment by nyakze** [comment]
> Problem solved.

What was causing the issue? How did you solve it?
Please elaborate so others having this issue can solve it as well

**Comment by skydivematy** [comment]
I have also that problem... will be nice he will share his knowledge.

**Comment by castillojim24** [comment]
skydivematy, are you using hiveos?

If the case copy the files: libnvrtc-builtins.so and libnvrtc.so.10.2 to the folder /hive/miners/ethminer/kawpowminer/1.2.2

**Comment by skydivematy** [comment]
Thanks for your respond, i did it. Copy both files from /hive/lib folder to hive/miners/ethminer/kawpowminer/1.2.2 but still same error....
`terminate called after throwing an instance of 'cuda_runtime_error'                                                           
  what():  CUDA NVRTC error in func compileKernel at line 411 calling compileResult failed with error NVRTC_ERROR_BUILTIN_OPER
TION_FAILURE`

**Comment by nyakze** [comment]
It seems that it's the issue of HiveOS incorrecrly linking libraries. If you want to fix it yourself, try the steps below. Note that t-rex is using 10.0 which is also incorrectly linked, so do the same for that version as well.
Do the following:
`locate libnvrtc-builtins.so | grep 10.2`
check that the link is wrong (pointing to 9.2)
`ls -lah /hive/lib/libnvrtc-builtins.so`
`rm /hive/lib/libnvrtc-builtins.so && ln -s /hive/lib/libnvrtc-builtins.so.10.2 /hive/lib/libnvrtc-builtins.so`

**Comment by nyakze** [comment]
If above doesn't help, do `nvidia-driver-update`

**Comment by skydivematy** [comment]
nvidia driver 440.82, hiveos all latest updates

**Comment by nyakze** [comment]
> nvidia driver 440.82, hiveos all latest updates

Which linux kernel is hive running on? Is it 5.0.21?

**Comment by 1613557499** [comment]
ubuntu 20.04 encountered the same problem how to solve?
