### ISSUE TITLE
binary and libraries for SMOS

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [RavenCommunity/kawpowminer#81]
Can you release also binaries for Ubuntu18?
SimpleMining OS is base on Ubuntu 18 for now.

or if not...please give compile procedure - ready to use lines to paste in console :-)

**Comment by jeroz1** [comment]
The procedure is in the readme on the front page.

If you run into issues. Let us know!

**Comment by tymoteuszrogalewski** [comment]
got failed.

I did:
git clone https://github.com/RavenCommunity/kawpowminer.git
cd kawpowminer
git submodule update --init --recursive
mkdir build
cd build
cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DAPICORE=ON
and git this:

-- [cable ] Cable 0.2.14 initialized
-- [hunter] Initializing Hunter workspace (e14bc153a7f16d6a5eeec845fb0283c8fad8c358)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.23.214.tar.gz
-- [hunter]   -> /root/.hunter/_Base/Download/Hunter/0.23.214/e14bc15
CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:27 (message):
  error: downloading
  'https://github.com/ruslo/hunter/archive/v0.23.214.tar.gz' failed

    status_code: 77
    status_string: "Problem with the SSL CA cert (path? access rights?)"
    log:   Trying 140.82.121.3...

  Connected to github.com (140.82.121.3) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  error setting certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  Closing connection 0

make[2]: *** [Hunter-prefix/src/Hunter-stamp/Hunter-download] Error 1
make[1]: *** [CMakeFiles/Hunter.dir/all] Error 2
make: *** [all] Error 2

**Comment by tymoteuszrogalewski** [comment]
This is very good information ;-)
Thanks
And I wish all newer version also binary distributed for Ub18 :) thx

**Comment by fdoving** [comment]
Binary uploaded.

Please give feedback if it works.
I did not have a chance to test it.

**Comment by tymoteuszrogalewski** [comment]
Thank, but start with error:

I did two test including cuda library 11.2 and also 11.2.1. Same error on both.

 i 15:22:55 kawpowminer Configured pool eu.rvn.minermore.com:4501
 i 15:22:55 kawpowminer Api server listening on port 3333.
 i 15:22:55 kawpowminer Selected pool eu.rvn.minermore.com:4501
 i 15:22:55 kawpowminer Stratum mode : Stratum
 i 15:22:55 kawpowminer Established connection to eu.rvn.minermore.com [136.244.92.193:4501]
 i 15:22:55 kawpowminer Spinning up miners...
cu 15:22:55 cuda-0    Using Pci Id : 01:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.80 GB
cu 15:22:55 cuda-1    Using Pci Id : 02:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.80 GB
cu 15:22:55 cuda-1    Releasing a primary context that has not been previously retained will fail with CUDA_ERROR_INVALID_CONTEXT, this is normal
cu 15:22:55 cuda-0    Releasing a primary context that has not been previously retained will fail with CUDA_ERROR_INVALID_CONTEXT, this is normal
cu 15:22:55 cuda-3    Using Pci Id : 05:00.0 GeForce RTX 2080 (Compute 7.5) Memory : 7.80 GB
cu 15:22:55 cuda-3    Releasing a primary context that has not been previously retained will fail with CUDA_ERROR_INVALID_CONTEXT, this is normal
 i 15:22:55 kawpowminer Extranonce set to 2244
cu 15:22:55 cuda-5    Using Pci Id : 07:00.0 Graphics Device (Compute 8.6) Memory : 7.80 GB
cu 15:22:55 cuda-5    Releasing a primary context that has not been previously retained will fail with CUDA_ERROR_INVALID_CONTEXT, this is normal
cu 15:22:55 cuda-4    Using Pci Id : 06:00.0 GeForce RTX 3070 (Compute 8.6) Memory : 7.80 GB
cu 15:22:55 cuda-2    Using Pci Id : 03:00.0 GeForce GTX 1080 Ti (Compute 6.1) Memory : 7.80 GB
cu 15:22:55 cuda-2    Releasing a primary context that has not been previously retained will fail with CUDA_ERROR_INVALID_CONTEXT, this is normal
 i 15:22:55 kawpowminer New target set to: 00000009f6000000000000000000000000000000000000000000000000000000
 i 15:22:55 kawpowminer Epoch : 229 Difficulty : 431.17 Mh
 i 15:22:55 kawpowminer Job: bb61edad… block 1724412 eu.rvn.minermore.com [136.244.92.193:4501]
OC Core and Memory will apply in 50 seconds...
cu 15:23:01 cuda-0    Generating DAG + Light : 2.83 GB
cu 15:23:01 cuda-1    Generating DAG + Light : 2.83 GB
cu 15:23:01 cuda-2    Generating DAG + Light : 2.83 GB
cu 15:23:01 cuda-3    Generating DAG + Light : 2.83 GB
cu 15:23:01 cuda-4    Generating DAG + Light : 2.83 GB
cu 15:23:01 cuda-5    Generating DAG + Light : 2.83 GB
 i 15:23:01 kawpowminer Authorized worker RH2swPipTDBBNxEBdzWuNa4roBu6kFzoTz
 i 15:23:01 kawpowminer New API session from 127.0.0.1:36340
 m 15:23:01 kawpowminer 0:00 A0 0.00 h - cu0 0.00, cu1 0.00, cu2 0.00, cu3 0.00, cu4 0.00, cu5 0.00
 i 15:23:01 kawpowminer API : Method miner_getstat1 requested
 i 15:23:04 kawpowminer New API session from 127.0.0.1:36346
 i 15:23:04 kawpowminer API : Method miner_getstat1 requested
cu 15:23:06 cuda-4    Generated DAG + Light in 4,732 ms. 4.96 GB left.
terminate called after throwing an instance of 'cuda_runtime_error'
  what():  CUDA NVRTC error in func compileKernel at line 420 calling compileResult failed with error NVRTC_ERROR_BUILTIN_OPERATION_FAILURE

**Comment by fdoving** [comment]
It was built with cuda 11.3 - latest from Nvidia - is 11.2 default on SMOS?

**Comment by fdoving** [comment]
I will rebuild with cuda 11.2.1

**Comment by tymoteuszrogalewski** [comment]
You told that it was build with 11.3?
100% sure?
kawpowminer-v1.2.4# ./kawpowminer --help
./kawpowminer: error while loading shared libraries: libnvrtc.so.11.2: cannot open shared object file: No such file or directory

In SimpleMining I include that libcuda version files that miner require.

May be 11.2 or 11.2.1 or 11.3 - just please tell in binary package what exactly version is required.

With prev kawpowminer-1.2.3 I just included two files:
libnvrtc-builtins.so and libnvrtc.so.10.2 - both from cuda 10.2
and it works.

But with kawpowminer-1.2.4 i testes with two files from cuda 11.2 and 11.2.1 and got above error.
Did try also with libraries from 11.3 (with rename files to 11.2 because of miner dont work with 11.3 in file names) and also got same error.

**Comment by tymoteuszrogalewski** [comment]
hmm...still doesnt work
terminate called after throwing an instance of 'cuda_runtime_error'
what(): CUDA NVRTC error in func compileKernel at line 420 calling compileResult failed with error NVRTC_ERROR_BUILTIN_OPERATION_FAILURE


my dir contains files:
kawpowminer
libnvrtc-builtins.so
libnvrtc.so.11.2

can you include libcuda files in binary package? maybe something is different (but shouldnt. I ran many miner in past using this procedure)
Or some cuda more files are require by this version of miner? (with 1.2.3 only those two was needed to work...of course with some older cuda files :P)
If not, I will try redownload cuda11.2.1 package from official site and try again.

**Comment by tymoteuszrogalewski** [comment]
my test machine is running nvidia driver 465.24.02, which is in theory compatible with CUDA 11.3

**Comment by fdoving** [comment]
https://github.com/RavenCommunity/kawpowminer/issues/8

**Comment by fdoving** [comment]
files from the build-machine.
[libnvrtc.tar.gz](https://github.com/RavenCommunity/kawpowminer/files/6517720/libnvrtc.tar.gz)

**Comment by tymoteuszrogalewski** [comment]
It starts working ;-)

I always include only two files (without any links - just renamed primary files into such shorts) as I also did lastly with version 1.2.3:

kawpowminer-v1.2.3-cuda10.2 contains files:
kawpowminer
libnvrtc-builtins.so  
libnvrtc.so.10.2 
...this works

but version 1.2.4 is not working such way and requires all the files (two libs) and all (or some of them) links. Probably one of lib file is required to be seen with fully version number in file name.
All the miners that I prepare packages I did in above procedure. Maybe this was a reason that gminer (and few other miners) starts to include cuda libs in binary file (static linking or other method...I dont know...to have not such problems with running miner on every client machine. (that have only compatible nvidia driver installed without any BIIIIG cuda library package)

kawpowminer-v1.2.4-cuda11.2 contains:
kawpowminer  
libnvrtc-builtins.so
libnvrtc.so.11.2
...this package starts but gives cuda error as on top of this issue report
(to be clear: those two lib files was originaly libs, not just empty symlinks :XD)

kawpowminer-v1.2.4-cuda11.2 contains:
kawpowminer  
libnvrtc-builtins.so -> libnvrtc-builtins.so.11.2
libnvrtc-builtins.so.11.2 -> libnvrtc-builtins.so.11.2.142
libnvrtc-builtins.so.11.2.142  
libnvrtc.so -> libnvrtc.so.11.2
libnvrtc.so.11.2 -> libnvrtc.so.11.2.142
libnvrtc.so.11.2.142
...this packages starts and mining :)

Thanks for support and have a nice day :)

**Comment by fdoving** [comment]
Ok, so you have to include the symlinks for it to work?

**Comment by tymoteuszrogalewski** [comment]
yes. exactly.

**Comment by fdoving** [comment]
Thank you for great feedback.

Does the 11.3 version (the ubuntu18 one on the release page) also work with the symlinks?

**Comment by tymoteuszrogalewski** [comment]
Yes. I include 11.3 libs like below and it works and mining

-rwxrwxrwx 1 root root 25945496 May 21 09:35 kawpowminer
lrwxrwxrwx 1 root root       25 May 21 09:34 libnvrtc-builtins.so -> libnvrtc-builtins.so.11.3
lrwxrwxrwx 1 root root       28 May 21 09:34 libnvrtc-builtins.so.11.3 -> libnvrtc-builtins.so.11.3.58
-rwxrwxrwx 1 root root  6672400 May 21 09:34 libnvrtc-builtins.so.11.3.58
lrwxrwxrwx 1 root root       16 May 21 09:34 libnvrtc.so -> libnvrtc.so.11.2
lrwxrwxrwx 1 root root       19 May 21 09:34 libnvrtc.so.11.2 -> libnvrtc.so.11.3.58
-rwxrwxrwx 1 root root 44378320 May 21 09:34 libnvrtc.so.11.3.58

**Comment by fdoving** [comment]
Great, thanks for all your testing and feedback.
