### ISSUE TITLE
.dll error amd rx570

### ISSUE THREAD

**Issue by tpebic** [RavenCommunity/kawpowminer#85]
I am getting a missing nvcuda.dll error on my system with a single amd rx570, not sure if it supports amd or not. 

Do I need to download those drivers? 

Your set up procedure is lacking support to remove these questions… :)

I couldn’t find much documentation online on how to add parameters into the bat file. 

If I’m doing something wrong I can’t say for sure as I’m newer to mining.

**Comment by fdoving** [comment]
Built OpenCL-only binaries for Windows and Ubuntu 20, you can find them here:

https://github.com/RavenCommunity/kawpowminer/releases/tag/1.2.4
