### ISSUE TITLE
Unexpected CUDA Error

### ISSUE THREAD

**Issue by Dirkadin** [RavenCommunity/kawpowminer#9]
Windows 10 1909 Build 18363.778
Nvidia driver 445.87
CUDA 10.2.89_441.22
GPU 2080 Ti

kawpowminer 1.1.3+commit.d8f61789
Build: windows/release/msvc

No OpenCL platforms found
 i 09:17:57 main      Configured pool rvnt.minermore.com:4505
 i 09:17:57 <unknown> Selected pool rvnt.minermore.com:4505
 i 09:17:57 <unknown> Stratum mode : Stratum
 i 09:17:57 <unknown> Established connection to rvnt.minermore.com [149.28.243.216:4505]
 i 09:17:57 <unknown> Spinning up miners...
cu 09:17:57 cuda-0    Using Pci Id : 01:00.0 GeForce RTX 2080 Ti (Compute 7.5) Memory : 11.00 GB
 i 09:17:57 <unknown> New target set to: 00000009f6000000000000000000000000000000000000000000000000000000
 i 09:17:57 <unknown> Epoch : 36 Difficulty : 431.17 Mh
 i 09:17:57 <unknown> Job: 5ad9206c... block 275934 rvnt.minermore.com [149.28.243.216:4505]
 i 09:17:57 <unknown> Authorized worker RGjTV2adxWDVrVqiUd7ZEeeVuF6v7yrwtQ.worker
cu 09:17:57 cuda-0    Generating DAG + Light : 1.30 GB
cu 09:17:57 cuda-0    Unexpected error CUDA error in func set_constants at line 180 calling cudaMemcpyToSymbol(d_dag, &_dag, sizeof(hash64_t*)) failed with error invalid device symbol on CUDA device 01:00.0
cu 09:17:57 cuda-0    Mining suspended ...
 m 09:18:02 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 09:18:02 main      Got interrupt ...
 i 09:18:02 main      Disconnected from rvnt.minermore.com [149.28.243.216:4505]
 i 09:18:02 main      Shutting down miners...
 i 09:18:02 main      Terminated!

**Comment by Dirkadin** [comment]
Looks like there was a fix mentioning this same error that hasn't had a release yet?

**Comment by blondfrogs** [comment]
fixed in #7
