### ISSUE TITLE
trying to mine RVN from my own node

### ISSUE THREAD

**Issue by mReArVlEiNn** [RavenCommunity/kawpowminer#93]
Hi.  I'm not sure if this is the place, but I'm trying to mine ravencoin using my own node.  I have the node setup properly to allow rpc, user, password, allowip, open port, listen, but I can't get the miner to work.  I'm using the getwork scheme.  My .bat file looks like this kawpowminer.exe -P getwork://user:pass@IP:port

**Comment by mReArVlEiNn** [comment]
It says Error reading from :IP:port : End of file
Disconnected from IP:port
No connection.  Suspend mining ...
Selected pool IP:port
Established connection to IP:port 
Resume mining ...
Then repeats this same string over and over.

**Comment by fdoving** [comment]
Not supported.
