### ISSUE TITLE
Compile issue.

### ISSUE THREAD

**Issue by PaS3** [RavenCommunity/kawpowminer#94]
How do I compile on Ubuntu 16.04.7 LTS Xenial   ( about to switch to 18.04)

nvcc fatal   : Unsupported gpu architecture 'compute_60'

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

What are the version does it need to compile ?

**Comment by fdoving** [comment]
You'll have to update to a newer version of the nvidia drivers.
